# name this file 'solutions.psy'
"""Volume II Lab 13: Optimization Packages I (scipy.optimize)
<Name> Matt Gong
<Class>
<Date>
"""

import numpy as np
from scipy import optimize as opt
from matplotlib import pyplot as plt

def prob1():
    """Use the minimize() function in the scipy.optimize package to find the
    minimum of the Rosenbrock function (scipy.optimize.rosen) using the
    following methods:
        Nelder-Mead
        Powell
        CG
        BFGS
        Newton-CG (test with and without the hessian)
        Anneal
        L-BFGS-B
        TNC
        COBYLA
        SLSQP
    Use x0 = np.array([4., -2.5]) for the initial guess for each test.
    
    Print a statement answering the following questions:
        Which algorithm(s) take(s) the least number of iterations?
        Which algorithm(s) fail to find the (correct) minimum?
    """

    x0 = np.array([4.,-2.5])
    rosen = opt.rosen
    hess = opt.rosen_hess
    grad = opt.rosen_der

    print "Nelder-Mead \n", opt.minimize(rosen, x0, method="Nelder-Mead", options={'xtol':1e-8})
    print "Powell\n",       opt.minimize(rosen, x0, method="Powell", options={'xtol':1e-8})
    print "CG\n",           opt.minimize(rosen, x0, method="CG", options={'gtol':1e-8})
    print "BFGS\n",         opt.minimize(rosen, x0, method="BFGS", options={'gtol':1e-8})

    #both version of newton
    print "Newton-CG Rosen\n", opt.minimize(rosen, x0, jac=grad,method="Newton-CG", options={'xtol':1e-8})
    print "Newton-CG hess\n",  opt.minimize(rosen, x0, jac=grad, hess = hess, method="Newton-CG", options={'xtol':1e-8})
    
    print "L-BFGS-B\n", opt.minimize(rosen, x0, method="L-BFGS-B", options={'gtol':1e-8})
    print "TNC\n",      opt.minimize(rosen, x0, method="TNC", options={'xtol':1e-8})
    print "COBYLA\n",   opt.minimize(rosen, x0, method="COBYLA", options={'tol':1e-8})
    print "SLSQP\n",    opt.minimize(rosen, x0, method="SLSQP", options={'ftol':1e-8})

    print "Powell converged after 19 iterations, CG failed, BFGS failed and COBYLA for iteration timing. All the others worked at varying levels of iterations ranging from 27-96"

def prob2():
    """Explore the documentation on the function scipy.optimize.basinhopping()
    online or via IPython. Use it to find the global minimum of the multmin()
    function given in the lab, with initial point x0 = np.array([-2, -2]) and
    the Nelder-Mead algorithm. Try it first with stepsize=0.5, then with
    stepsize=0.2.

    Return the minimum value of the function with stepsize=0.2.
    Print a statement answering the following question:
        Why doesn't scipy.optimize.basinhopping() find the minimum the second
        time (with stepsize=0.2)?
    """

    def multimin(x):
        r = np.sqrt((x[0]+1)**2 + x[1]**2)
        return r**2 *(1+ np.sin(4*r)**2)

    x0 = np.array([-2.,2.])

    print "step size = 0.5", opt.basinhopping(multimin, x0, stepsize=0.5, minimizer_kwargs={'method':'nelder-mead'})
    print "step size = 0.2", opt.basinhopping(multimin, x0, stepsize=0.2, minimizer_kwargs={'method':'nelder-mead'})

    print "The stepsize matters, if it's too small then it won't ever leave the basin and if it's too big then it can overshoot and require a lot of backtracking"

def prob3():
    """Find the roots of the system
    [       -x + y + z     ]   [0]
    [  1 + x^3 - y^2 + z^3 ] = [0]
    [ -2 - x^2 + y^2 + z^2 ]   [0]

    Returns the values of x,y,z as an array.
    """

    def funcs(x):
        a = x[1] + x[2] - x[0]
        b = 1. + x[0]**3 + x[2]**3 - x[1]**2
        c = x[1]**2 - 2. + x[2]**2 - x[0]**2
        
        return a,b,c

    def jac(x):
        n = np.array([[-1,1,1],
                      [3*x[0]**2, -3*x[1]**2, 3*x[2]**2],
                      [-2*x[0], 2*x[1], 2*x[2]]])
        return n

    sol = opt.root(funcs, [0,0,0], jac=jac, method='hybr')

    print sol.x

    return sol.x

def prob4():
    """Use the scipy.optimize.curve_fit() function to fit a heating curve to
    the data found in `heating.txt`. The first column of this file is time, and
    the second column is temperature in Kelvin.

    The fitting parameters should be gamma, C, and K, as given in Newton's law
    of cooling.

    Plot the data from `heating.txt` and the curve generated by curve_fit.
    Return the values gamma, C, K as an array.
    """
    def newton_cool(time,gamma,C,K):
        number = 290. + 59.43/gamma + K*np.exp(-(gamma*time/C))
        return number
    data = np.loadtxt('heating.txt')

    popt,pcov = opt.curve_fit(newton_cool,data[:,0],data[:,1])

    y = newton_cool(data[:,0], popt[0],popt[1],popt[2])

    plt.plot(data[:,0],data[:,1])
    plt.plot(data[:,0], y)

    plt.show()


    return popt

